/**
 * TreeVisualizer — Decision Tree Visualization
 */
var TreeVisualizer=(function(){var canvas,ctx,w,h;var mg={left:55,bottom:45,top:15,right:15};
function rng(s){var z=s|0;return function(){z=(z*1103515245+12345)&0x7fffffff;return(z>>16)/32768}}
function genData(n,p){var r=rng(n*137),d=[];
if(p==="circle"){for(var i=0;i<n;i++){var x=r()*8-4,y=r()*8-4,dist=Math.sqrt(x*x+y*y),l=dist<2?0:1;if(r()<0.08)l=1-l;d.push({x:x,y:y,label:l})}}
else if(p==="stripes"){for(var j=0;j<n;j++){var sx=r()*8-4,sy=r()*8-4,sl=Math.floor((sy+4)/2.5)%2;if(r()<0.08)sl=1-sl;d.push({x:sx,y:sy,label:sl})}}
else{for(var k=0;k<n;k++){var qx=r()*8-4,qy=r()*8-4,ql=(qx>0&&qy>0)||(qx<=0&&qy<=0)?0:1;if(r()<0.05)ql=1-ql;d.push({x:qx,y:qy,label:ql})}}
return d}
function gini(gs){var t=0,i;for(i=0;i<gs.length;i++)t+=gs[i].length;if(t===0)return 0;var imp=0;for(i=0;i<gs.length;i++){var g=gs[i];if(g.length===0)continue;var p0=0,p1=0;for(var k=0;k<g.length;k++){if(g[k].label===0)p0++;else p1++}var rt=g.length/t;imp+=rt*(1-(p0/g.length)*(p0/g.length)-(p1/g.length)*(p1/g.length))}return imp}
function mj(d){var c0=0,c1=0;for(var i=0;i<d.length;i++){if(d[i].label===0)c0++;else c1++}return c0>=c1?0:1}
function bstSplt(d){if(d.length<=1)return null;var bG=Infinity,bF=-1,bT=0,bGrp=null;for(var f=0;f<2;f++){var vs=[];for(var i=0;i<d.length;i++)vs.push(f===0?d[i].x:d[i].y);vs.sort(function(a,b){return a-b});for(var j=0;j<vs.length-1;j++){var th=(vs[j]+vs[j+1])/2;var left=[],right=[];for(var k=0;k<d.length;k++){var val=f===0?d[k].x:d[k].y;if(val<=th)left.push(d[k]);else right.push(d[k])}var g=gini([left,right]);if(g<bG){bG=g;bF=f;bT=th;bGrp=[left,right]}}}if(!bGrp||bGrp[0].length===0||bGrp[1].length===0)return null;return{feature:bF,threshold:bT,left:bGrp[0],right:bGrp[1],gini:bG}}
function bldTree(d,depth,maxD){var pred=mj(d);if(depth>=maxD||d.length<=2)return{type:"leaf",prediction:pred};var sr=bstSplt(d);if(!sr)return{type:"leaf",prediction:pred};if(gini([d])-sr.gini<0.001)return{type:"leaf",prediction:pred};return{type:"node",feature:sr.feature,threshold:sr.threshold,left:bldTree(sr.left,depth+1,maxD),right:bldTree(sr.right,depth+1,maxD)}}
function pred(tree,x,y){if(tree.type==="leaf")return tree.prediction;var val=tree.feature===0?x:y;if(val<=tree.threshold)return pred(tree.left,x,y);else return pred(tree.right,x,y)}
function cntNodes(tree){if(!tree)return 0;if(tree.type==="leaf")return 1;return 1+cntNodes(tree.left)+cntNodes(tree.right)}
function init(id,cfg){cfg=cfg||{};canvas=document.getElementById(id);if(!canvas)return;ctx=canvas.getContext("2d");w=canvas.width;h=canvas.height;var n=cfg.n||50,maxD=cfg.maxDepth||3,pt=cfg.pattern||"quadrants";var d=genData(n,pt);var tree=bldTree(d,0,maxD);draw(d,tree,maxD,pt)}
function draw(d,tree,maxD,pt){ctx.clearRect(0,0,w,h);var pw=w-mg.left-mg.right,ph=h-mg.top-mg.bottom;var xMn=-4.5,xMx=4.5,yMn=-4.5,yMx=4.5;function tx(v){return mg.left+(v-xMn)/(xMx-xMn)*pw}function ty(v){return mg.top+(1-(v-yMn)/(yMx-yMn))*ph}var gd=80;for(var gi=0;gi<gd;gi++){for(var gj=0;gj<gd;gj++){var cx=xMn+(xMx-xMn)*(gi+.5)/gd,cy=yMn+(yMx-yMn)*(gj+.5)/gd;var p=pred(tree,cx,cy);ctx.fillStyle=p===0?"rgba(59,130,246,0.18)":"rgba(239,68,68,0.18)";ctx.fillRect(tx(cx)-pw/gd/2,ty(cy)-ph/gd/2,pw/gd+1,ph/gd+1)}}ctx.strokeStyle="#cbd5e1";ctx.lineWidth=.5;for(var ai=-4;ai<=4;ai++){var ax=tx(ai);ctx.beginPath();ctx.moveTo(ax,mg.top);ctx.lineTo(ax,mg.top+ph);ctx.stroke();var ay=ty(ai);ctx.beginPath();ctx.moveTo(mg.left,ay);ctx.lineTo(mg.left+pw,ay);ctx.stroke()}ctx.strokeStyle="#94a3b8";ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(mg.left,ty(0));ctx.lineTo(mg.left+pw,ty(0));ctx.moveTo(tx(0),mg.top);ctx.lineTo(tx(0),mg.top+ph);ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle="#475569";ctx.beginPath();ctx.moveTo(mg.left,mg.top);ctx.lineTo(mg.left,mg.top+ph);ctx.moveTo(mg.left,mg.top+ph);ctx.lineTo(mg.left+pw,mg.top+ph);ctx.stroke();ctx.fillStyle="#64748b";ctx.font="10px sans-serif";ctx.textAlign="center";for(var ti=-4;ti<=4;ti+=2)ctx.fillText(ti,tx(ti),mg.top+ph+14);ctx.textAlign="right";for(var tj=-4;tj<=4;tj+=2)ctx.fillText(tj,mg.left-5,ty(tj)+4);ctx.textAlign="center";ctx.fillText("x",mg.left+pw/2,mg.top+ph+34);ctx.save();ctx.translate(10,mg.top+ph/2);ctx.rotate(-Math.PI/2);ctx.fillText("y",0,0);ctx.restore();for(var di=0;di<d.length;di++){var pt=d[di];ctx.beginPath();ctx.arc(tx(pt.x),ty(pt.y),4,0,Math.PI*2);ctx.fillStyle=pt.label===0?"#3b82f6":"#ef4444";ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=.8;ctx.stroke()}var cr=0;for(var j=0;j<d.length;j++){if(pred(tree,d[j].x,d[j].y)===d[j].label)cr++}var acc=(cr/d.length*100).toFixed(1);var lx=mg.left+pw-210,ly=mg.top+8;ctx.fillStyle="#3b82f6";ctx.fillRect(lx,ly,10,10);ctx.fillStyle="#1e293b";ctx.font="11px sans-serif";ctx.textAlign="left";ctx.fillText("Class 0",lx+14,ly+9);ly+=16;ctx.fillStyle="#ef4444";ctx.fillRect(lx,ly,10,10);ctx.fillText("Class 1",lx+14,ly+9);ly+=18;ctx.fillStyle="#1e293b";ctx.font="bold 11px sans-serif";ctx.fillText("Nodes: "+cntNodes(tree)+"  |  Depth: "+maxD+"  |  Acc: "+acc+"%",lx,ly+9);ly+=16;ctx.font="11px sans-serif";ctx.fillText("Pattern: "+pt,lx,ly+9)}
return{init:init}})();